Task: 0x05-python-exceptions
